Vagrant.configure("2") do |config|
  config.vm.box = "almalinux.box"
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum update
    sudo yum install epel-release -y
    sudo yum install ansible -y
    sudo yum clean all
    history -c
  SHELL
end
