---

- ansible.builtin.template:
    src: "gearman-inventory.py.j2"
    dest: "/usr/local/sbin/gearman-inventory.py"
  notify: "Restart gearman-inventory"
  when: gearman_job == "inventory"

- ansible.builtin.template:
    src: "gearman-ansible.py.j2"
    dest: "/usr/local/sbin/gearman-ansible.py"
  notify: "Restart gearman-ansible"
  when: gearman_job == "ansible"