---

- ansible.builtin.copy:
    src: "worker.service"
    dest: "/etc/systemd/system/gearman-inventory.service"
  notify: "Restart gearman-inventory"

- ansible.builtin.systemd:
    name: "gearman-inventory"
    enabled: "yes"
    state: "started"
    daemon_reload: "yes"