---

- ansible.builtin.copy:
    src: "gearman-inventory.service"
    dest: "/etc/systemd/system/gearman-inventory.service"
  notify: "Restart gearman-inventory"
  when: gearman_job == "inventory"

- ansible.builtin.copy:
    src: "gearman-ansible.service"
    dest: "/etc/systemd/system/gearman-ansible.service"
  notify: "Restart gearman-ansible"
  when: gearman_job == "ansible"

- ansible.builtin.systemd:
    name: "gearman-inventory"
    enabled: "yes"
    state: "started"
    daemon_reload: "yes"
  when: gearman_job == "inventory"

- ansible.builtin.systemd:
    name: "gearman-ansible"
    enabled: "yes"
    state: "started"
    daemon_reload: "yes"
  when: gearman_job == "ansible"