---
- hosts: all
  remote_user: ansible
  become: true
  vars:
    gearman:
      proxy: "192.168.0.152"
      servers:
        - "192.168.0.153"
  tasks:

    - debug:
        msg: "{{ ansible_distribution }}/{{ ansible_distribution_major_version }}"

    - debug:
        var: ansible_local['roles']

    - include_role:
        name: "{{ item }}"
      with_items: "{{ ansible_local['roles'] | default('gearman-common') }}"

    - ansible.builtin.file:
        path: "/etc/ansible/facts.d/"
        state: "directory"

    - ansible.builtin.copy:
        content: "{{ ansible_local['roles'] | to_nice_json }}"
        dest: "/etc/ansible/facts.d/roles.fact"
