---
- hosts: all
  remote_user: ansible
  become: true
  tasks:

    - debug:
        msg: "{{ ansible_distribution }}/{{ ansible_distribution_major_version }}"

    - debug:
        var: ansible_local['roles'] | default('gearman-common')

    - name: "Include applicable roles"
      include_role:
        name: "{{ item }}"
      with_items: "{{ ansible_local['roles'] | default('gearman-common') }}"

    - ansible.builtin.file:
        path: "/etc/ansible/facts.d/"
        state: "directory"

    - ansible.builtin.copy:
        content: "{{ ansible_local['roles'] | default('gearman-common') | to_nice_json }}"
        dest: "/etc/ansible/facts.d/roles.fact"
