---
- hosts: all
  remote_user: vagrant
  become: true
  tasks:

    - debug:
        msg: "{{ ansible_distribution }}/{{ ansible_distribution_major_version }}"

    - include_role:
        name: "{{ item }}"
      with_items: "{{ ansible_local['roles'] | default('gearman-client') }}"

    - ansible.builtin.file:
        path: "/etc/ansible/facts.d/"
        state: "directory"

    - ansible.builtin.copy:
        content: "{{ ansible_local['roles'] | default(['gearman-client']) | to_nice_json }}"
        dest: "/etc/ansible/facts.d/roles.fact"
