---
- hosts: all
  remote_user: ansible
  become: true
  tasks:

    - debug:
        msg: "{{ ansible_hostname }} ==> {{ ansible_distribution }}/{{ ansible_distribution_major_version }}"

    - name: "Include {{ role }} role"
      include_role:
        name: "{{ role }}"

    - ansible.builtin.copy:
        content: "{{ ansible_local['roles'] | default([]) | union([role]) | to_nice_json }}"
        dest: "/etc/ansible/facts.d/roles.fact"
