---
- hosts: all
  remote_user: ansible
  become: true
  tasks:

    - ansible.builtin.copy:
        content: "{{ group_names | to_nice_json }}"
        dest: "/etc/ansible/facts.d/roles.fact"

    - ansible.builtin.copy:
        content: "{{ groups['gearman-server'] | to_nice_json }}"
        dest: "/etc/ansible/facts.d/gearman.fact"

    - name: "Include 'gearman-common' role"
      include_role:
        name: "gearman-common"

    - name: "Include misc roles"
      include_role:
        name: "{{ item }}"
      with_items: "{{ group_names }}"
