---
- hosts: all
  remote_user: ansible
  become: true
  tasks:

    - ansible.builtin.add_host:
        name: '{{ item }}'
        groups: "{{ hostvars[item]['ansible_local']['roles'] }}"
      loop: "{{ ansible_play_hosts }}"

    - name: Output groups
      debug:
        var: groups
        verbosity: 1
      delegate_to: localhost
      run_once: true
