---

- name: "Debian packages"
  ansible.builtin.apt:
    name: "gearman-tools"
  when: ansible_distribution == "Debian"

- name: "Ubuntu packages"
  ansible.builtin.apt:
    name: "gearman-tools"
  when: ansible_distribution == "Ubuntu"

- name: "AlmaLinux packages"
  ansible.builtin.dnf:
    name:
      - "epel-release"
      - "gearmand"
  when: ansible_distribution == "AlmaLinux"

- name: "Rocky packages"
  ansible.builtin.dnf:
    name:
      - "epel-release"
      - "gearmand"
  when: ansible_distribution == "Rocky"

- name: "CentOS7 packages"
  ansible.builtin.yum:
    name:
      - "epel-release"
      - "gearmand"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"