---

- name: "Debian package"
  ansible.builtin.apt:
    name: "gearman-tools"
  when: ansible_distribution == "Debian"

- name: "Ubuntu package"
  ansible.builtin.apt:
    name: "gearman-tools"
  when: ansible_distribution == "Ubuntu"

- name: "AlmaLinux package"
  ansible.builtin.dnf:
    name: "epel-release"
  when: ansible_distribution == "AlmaLinux"

- name: "AlmaLinux package"
  ansible.builtin.dnf:
    name: "gearmand"
  when: ansible_distribution == "AlmaLinux"

- name: "Rocky package"
  ansible.builtin.dnf:
    name: "epel-release"
  when: ansible_distribution == "Rocky"

- name: "Rocky package"
  ansible.builtin.dnf:
    name: "gearmand"
  when: ansible_distribution == "Rocky"

- name: "CentOS7 package"
  ansible.builtin.yum:
    name: "epel-release"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: "CentOS7 package"
  ansible.builtin.yum:
    name: "gearmand"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"