---

- debug:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_major_version }}"

- ansible.builtin.include_tasks:
    file: install.yml

- ansible.builtin.include_tasks:
    file: configure.yml

- ansible.builtin.include_tasks:
    file: service.yml
