---

- name: "Debian package update"
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: "Debian gearman package"
  ansible.builtin.apt:
    name: "python3-pip"
  when: ansible_distribution == "Debian"

- name: "Ubuntu package update"
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: "Ubuntu gearman package"
  ansible.builtin.apt:
    name: "gearman-tools"
  when: ansible_distribution == "Ubuntu"

- name: "AlmaLinux epel package"
  ansible.builtin.dnf:
    name: "epel-release"
  when: ansible_distribution == "AlmaLinux"

- name: "AlmaLinux gearmand package"
  ansible.builtin.dnf:
    name: "gearmand"
  when: ansible_distribution == "AlmaLinux"

- name: "Rocky epel package"
  ansible.builtin.dnf:
    name: "epel-release"
  when: ansible_distribution == "Rocky"

- name: "Rocky gearmand package"
  ansible.builtin.dnf:
    name: "gearmand"
  when: ansible_distribution == "Rocky"

- name: "CentOS7 epel package"
  ansible.builtin.yum:
    name: "epel-release"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: "CentOS7 gearmand package"
  ansible.builtin.yum:
    name: "gearmand"
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"

- name: "Asynchronous Event-Driven Gearman Interface"
  ansible.builtin.pip:
    name: "gear"

- ansible.builtin.copy:
    src: "gearman.py"
    dest: "/usr/local/sbin/gearman.py"
    mode: "0755"

- ansible.builtin.find:
    paths: "/etc/ansible/roles"
    file_type: "directory"
  delegate_to: localhost
  register: search

- ansible.builtin.template:
    src: "management.py.j2"
    dest: "/usr/local/sbin/management.py"
    mode: "0755"
  vars:
    roles: "{{ search.files | map(attribute='path') | map('regex_replace', '/etc/ansible/roles/') }}"
