---

- name: "Debian package update"
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_distribution == "Debian"

- name: "Debian python3 installer"
  ansible.builtin.apt:
    name: "python3"
  when: ansible_distribution == "Debian"

- name: "Debian prometheus-node-exporter installer"
  ansible.builtin.apt:
    name: "prometheus-node-exporter"
  when: ansible_distribution == "Debian"

- name: "Ubuntu package update"
  ansible.builtin.apt:
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: "Ubuntu python3 installer"
  ansible.builtin.apt:
    name: "python3"
  when: ansible_distribution == "Ubuntu"

- name: "Ubuntu prometheus-node-exporter installer"
  ansible.builtin.apt:
    name: "prometheus-node-exporter"
  when: ansible_distribution == "Ubuntu"

- name: "Python package installer"
  ansible.builtin.package:
    name: "python3-pip"

- name: "Asynchronous Event-Driven Gearman Interface"
  ansible.builtin.pip:
    name: "gear"

- ansible.builtin.copy:
    src: "inventory.py"
    dest: "/usr/local/sbin/inventory.py"
    mode: "0755"

- ansible.builtin.copy:
    src: "ansible.py"
    dest: "/usr/local/sbin/ansible.py"
    mode: "0755"

- ansible.builtin.find:
    paths: "/etc/ansible/roles"
    file_type: "directory"
  delegate_to: localhost
  register: search

- ansible.builtin.template:
    src: "management.py.j2"
    dest: "/usr/local/sbin/management.py"
    mode: "0755"
  vars:
    roles: "{{ search.files | map(attribute='path') | map('regex_replace', '/etc/ansible/roles/') }}"
