---

- ansible.builtin.cron:
    name: "Reboot marker"
    special_time: "reboot"
    job: "/usr/local/sbin/gearman.py `hostname -I | awk '{ print $NF }'`"
    user: "ansible"

- ansible.builtin.cron:
    name: "Hourly marker"
    special_time: "hourly"
    job: "/usr/local/sbin/gearman.py `hostname -I | awk '{ print $NF }'`"
    user: "ansible"

- ansible.builtin.systemd:
    name: "prometheus"
    enabled: "yes"
    state: "started"
    daemon_reload: "yes"
