Vagrant.configure("2") do |config|
  config.vm.box = "gearman.box"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    sudo apt-get install ansible -y
    sudo apt-get clean
    history -c
  SHELL
end
