---

- ansible.builtin.copy:
    src: "gearman-job-server"
    dest: "/etc/default/gearman-job-server"
  notify: "Restart gearman-server"

- ansible.builtin.blockinfile:
    path: "/etc/prometheus/prometheus.yml"
    block: |2
        - job_name: gearman
          static_configs:
            - targets:
              - '192.168.0.152:9418'
              - '192.168.0.153:9418'
  notify: "Restart prometheus"
