---

- name: "Restart gearman-server"
  ansible.builtin.systemd:
    name: "gearman-job-server"
    state: "restarted"

- name: "Restart gearman-exporter"
  ansible.builtin.systemd:
    name: "gearman-exporter"
    state: "restarted"
