---

- ansible.builtin.git:
    repo: 'https://github.com/vittrupconsulting/gearman-ansible.git'
    dest: "/etc/.ansible"

-  ansible.posix.synchronize:
     src: "/etc/.ansible"
     dest: "/etc/ansible"
     rsync_opts:
         - "--exclude=.git"
   delegate_to: "{{ inventory_hostname }}"

- ansible.builtin.file:
    path: "/etc/ansible/ansible_rsa"
    mode: "0700"

