---

- ansible.builtin.git:
    repo: 'https://github.com/vittrupconsulting/gearman-ansible.git'
    dest: "/etc/.ansible"
    version: "{{ gearman.ansible.branch | default('HEAD') }}"

- ansible.posix.synchronize:
    src: "/etc/.ansible/"
    dest: "/etc/ansible"
    rsync_opts:
      - "--exclude=.git"
      - "--exclude=ansible_rsa"
      - "--chown=ansible:ansible"
  delegate_to: "{{ inventory_hostname }}"

- ansible.builtin.copy:
    src: "/etc/.ansible/ansible_rsa"
    dest: "/etc/ansible/ansible_rsa"
    mode: "0600"
    owner: "ansible"
    group: "ansible"
    remote_src: yes

- ansible.builtin.copy:
    src: "/etc/.ansible/roles/gearman-ansible/files/inventory.py"
    dest: "/etc/ansible/inventory.py"
    mode: "0755"
    owner: "ansible"
    group: "ansible"
    remote_src: yes

- ansible.builtin.copy:
    src: "/etc/.ansible/roles/gearman-ansible/files/ansible.cfg"
    dest: "/etc/ansible/ansible.cfg"
    owner: "ansible"
    group: "ansible"
    remote_src: yes
