Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    sudo apt-get install python3-pip nmap curl -y
    sudo pip install gear
    sudo useradd ansible --system --create-home --shell /bin/bash
    echo 'ansible ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/ansible
    sudo su root --login --command "/usr/bin/mkdir /etc/ansible"
    sudo su root --login --command "/usr/bin/mkdir /etc/ansible/facts.d"
    sudo su root --login --command "/usr/bin/chown -R vagrant:vagrant /etc/ansible"
    sudo su ansible --login --command "/usr/bin/mkdir /home/ansible/.ssh"
    sudo su ansible --login --command "/usr/bin/echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDO/b4LqHoJPSWLovBmo8jaj9RWNmtdSyoUJVd/0lnGQpTOgKhM6GA4K+sNIKSjZSRqVmp0qvYxNhMSGnnDzagsZY9ydfF0R5/2SAFI7ezn+z75LbyAx0vpk7e4KIxPatx7/YAABQMOa9dT/qPhSXJ9/YO4QYPFUA3AyMQLJwb5Am6jlqxYBpRe+zt8HUlat2HD628YBNKWyqSsL13kKt2QzaAHT75ZqPEHlQMA3Q/kjmAW4McqtQ6BhVwhGaneslbsj8A/fQGzxRQtW81MC7K83x7RSwV40NXcJeUEYcJyhD029dg74wA875Vv9S7Y4MF+OKO2w4bRm+1uyTIXSAhIsVWbB3uyoFz2EjfMEsSK6uqMGbbGyC7pTXz1qkX0tPWkkLvUTbjIs2FDCE+eWOI/neQ32jdMBsZujzJ8i4VdQeGUUfJATuRB6hjm1XEVx0wzRfNAGba2OxCjj9dx5URgVje55+POxDPPfpCaAL98/xCZmuP/SgYk44YIEqFXtXc=' | tee /home/ansible/.ssh/authorized_keys"
    sudo apt-get clean
    history -c
  SHELL
end
