---

- ansible.builtin.include_vars:
    file: "{{ ansible_hostname }}.yml"

- ansible.builtin.template:
    src: "etcd.service.j2"
    dest: "/etc/systemd/system/etcd.service"
  notify: "Restart etcd"

- ansible.builtin.systemd:
    name: "etcd"
    enabled: "yes"
    state: "started"
    daemon_reload: "yes"
