---

- ansible.builtin.include_vars:
    file: "{{ ansible_hostname }}.yml"

- ansible.builtin.file:
    path: "/tmp/etcd"
    state: "directory"
    owner: "ansible"
    group: "ansible"

#- ansible.builtin.template:
#    src: "etcd.j2"
#    dest: "/etc/default/etcd"
#  notify: "Restart etcd"

- ansible.builtin.copy:
    src: "etcd"
    dest: "/usr/bin/etcd"
    mode: "0755"
  notify: "Restart etcd"

- ansible.builtin.copy:
    src: "etcdctl"
    dest: "/usr/bin/etcdctl"
    mode: "0755"
  notify: "Restart etcd"

- ansible.builtin.template:
    src: "etcd.service.j2"
    dest: "/etc/systemd/system/etcd.service"
  notify: "Restart etcd"

- ansible.builtin.systemd:
    name: "etcd"
    enabled: "yes"
    state: "started"
    daemon_reload: "yes"

- ansible.builtin.blockinfile:
    path: "/etc/prometheus/prometheus.yml"
    block: |2
        - job_name: etcd
          static_configs:
            - targets:
              - '192.168.0.154:2379'
              - '192.168.0.155:2379'
              - '192.168.0.156:2379'
  notify: "Restart prometheus"