---

- ansible.builtin.wait_for:
    host: "192.168.0.170"
    port: "3000"
    sleep: "5"

- community.grafana.grafana_datasource:
    name: "etcd"
    ds_type: "prometheus"
    ds_url: "http://192.168.0.161:9090"
    tls_skip_verify: true
    grafana_url: "http://192.168.0.170:3000"
    url_username: "admin"
    url_password: "admin"
  ignore_errors: yes

- ansible.builtin.copy:
    src: "etcd.json"
    dest: "/opt/dashboards/etcd.json"

- community.grafana.grafana_dashboard:
    grafana_url: "http://192.168.0.170:3000"
    url_username: "admin"
    url_password: "admin"
    path: "/opt/dashboards/etcd.json"
    overwrite: "yes"
  ignore_errors: yes