{
 "title": "Gearman",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Usage (%)",
   "type": "graph",
   "description": "Shows what is the % usage of each workers in gearman.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(gearman_jobs/gearman_workers)*100",
     "legendFormat": "{{function}}"
    }
   ]
  },
  {
   "title": "Running",
   "type": "graph",
   "description": "Currently running jobs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gearman_jobs_running", "legendFormat": "{{function}}" }
   ]
  },
  {
   "title": "Waiting",
   "type": "graph",
   "description": "Jobs that are currently waiting because there is not enough workers to process them",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gearman_jobs_waiting", "legendFormat": "{{function}}" }
   ]
  }
 ]
}