#!/bin/bash

echo https://linuxhint.com/install-nagios-ubuntu-22-04/

sudo apt update

sudo apt install -y wget unzip curl openssl build-essential libgd-dev libssl-dev libapache2-mod-php php-gd php apache2

wget https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.7.tar.gz

sudo tar -zxvf nagios-4.4.7.tar.gz

sudo ./configure

sudo make all

sudo make install-groups-users

sudo usermod -a -G nagios www-data

sudo make install

sudo make install-commandmode

sudo make install-config

sudo make install-webconf

sudo a2enmod rewrite

sudo a2enmod cgi

sudo htpasswd -b -c /usr/local/nagios/etc/htpasswd.users admin admin

sudo wget https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz

sudo tar -zxvf nagios-plugins-2.3.3.tar.gz

sudo ./configure --with-nagios-user=nagios --with-nagios-group=nagios

sudo make install

sudo /usr/local/nagios/bin/nagios -v

sudo systemctl restart apache2
