---

- ansible.builtin.command: "echo https://linuxhint.com/install-nagios-ubuntu-22-04/"

- ansible.builtin.command: "apt update"
  become: true

- ansible.builtin.command: "apt install -y wget unzip curl openssl build-essential libgd-dev libssl-dev libapache2-mod-php php-gd php apache2"
  become: true

- ansible.builtin.command: "wget https://assets.nagios.com/downloads/nagioscore/releases/nagios-4.4.7.tar.gz"
  become: true

- ansible.builtin.command: "tar -zxvf nagios-4.4.7.tar.gz"
  become: true

- ansible.builtin.command: "./configure"
  become: true
  args:
    chdir: nagios-4.4.7

- ansible.builtin.command: "make all"
  become: true
  args:
    chdir: nagios-4.4.7

- ansible.builtin.command: "make install-groups-users"
  become: true
  args:
    chdir: nagios-4.4.7

- ansible.builtin.command: "usermod -a -G nagios www-data"
  become: true
  args:
    chdir: nagios-4.4.7

- ansible.builtin.command: "make install"
  become: true
  args:
    chdir: nagios-4.4.7

- ansible.builtin.command: "make install-commandmode"
  become: true
  args:
    chdir: nagios-4.4.7

- ansible.builtin.command: "make install-config"
  become: true
  args:
    chdir: nagios-4.4.7

- ansible.builtin.command: "make install-webconf"
  become: true
  args:
    chdir: nagios-4.4.7

- ansible.builtin.command: "a2enmod rewrite"
  become: true
  args:
    chdir: nagios-4.4.7

- ansible.builtin.command: "a2enmod cgi"
  become: true
  args:
    chdir: nagios-4.4.7

- ansible.builtin.command: "htpasswd -b -c /usr/local/nagios/etc/htpasswd.users admin admin"
  become: true
  args:
    chdir: nagios-4.4.7

- ansible.builtin.command: "wget https://nagios-plugins.org/download/nagios-plugins-2.3.3.tar.gz"
  become: true

- ansible.builtin.command: "tar -zxvf nagios-plugins-2.3.3.tar.gz"
  become: true

- ansible.builtin.command: "./configure --with-nagios-user=nagios --with-nagios-group=nagios"
  become: true
  args:
    chdir: nagios-plugins-2.3.3

- ansible.builtin.command: "make install"
  become: true
  args:
    chdir: nagios-plugins-2.3.3

- ansible.builtin.command: "/usr/local/nagios/bin/nagios -v"
  become: true
  args:
    chdir: nagios-plugins-2.3.3

- ansible.builtin.command: "systemctl restart apache2"
  become: true
  args:
    chdir: nagios-plugins-2.3.3
